# Generated by Django 6.0.1 on 2026-01-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Django Starter', max_length=255)),
                ('app_tagline', models.CharField(default='My Awesome Project', max_length=255)),
                ('app_author', models.CharField(default='Konstantinos Droulias', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
